// <auto-generated />
using FCloud3.Services.Etc.TempData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCloud3.Services.Etc.TempData.Migrations
{
    [DbContext(typeof(TempDataContext))]
    [Migration("20240421143029_CreateContentLock")]
    partial class CreateContentLock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FCloud3.Services.Etc.TempData.EditLock.ContentEditLock", b =>
                {
                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObjectType", "ObjectId");

                    b.ToTable("ContentEditLock");
                });
#pragma warning restore 612, 618
        }
    }
}
